fr = {'affichage_dev': {0: 'Fichier | a Propos | Configuration | Stock\n',
                        1: 'Recettes conseillees',
                        2: 'Produits bientot perimes',
                        3: 'A propos',
                        4: 'Erreur Config',
                        5: 'Config inexistante',
                        6: 'Produits',
                        7: 'Utilisateurs (supRimer, oUvrir config)',
                        8: 'commandes ([nombre][lettre]):',
                        9: 'Creer utilisateur',
                        10: 'Utilisateur',
                        11: 'Sur ?',
                        12: 'Etes-vous sur de vouloir supprimer ce compte ? Oui',
                        13: 'nom_utilisateur : ',
                        14: 'nom_cuisines :',
                        15: 'Nouvelle cuisine',
                        16: 'Cuisine',
                        17: 'nom : ',
                        18: 'Configuration',
                        19: '[U] : modifier profil Utilisateur'}}

liste_langues = {'fr': fr}
